CREATE  TABLE  DEPT_CONST(
  DEPTNO   NUMBER(2)  CONSTRAINT  DEPTCONST_DEPTNO_PK  PRIMARY KEY,
  DNAME    VARCHAR2(14)  CONSTRAINT  DEPTCONST_DNAME_UNIQ  UNIQUE,
  LOC      VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

CREATE  TABLE  EMP_CONST(
  EMPNO   NUMBER(2)  CONSTRAINT  EMPCONST_DEPTNO_PK  PRIMARY KEY,
  ENAME    VARCHAR2(14)  CONSTRAINT  EMPCONST_DNAME_UNIQ  UNIQUE,
  JOB   VARCHAR2(13) CONSTRAINT EMPCONST_LOC_NN NOT NULL,
  TEL   VARCHAR(9),
  HIREDATE DATE,
  SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK NULL,
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2)CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

DESC DEPT_CONST;
DESC EMP_CONST;


--1. EMP테이블에서 이름에 A가 포함된 사원에 대해서 앞 3글자만 추출하는 SQL작성.
SELECT SUBSTR(ENAME,1,3) NAME
FROM EMP
WHERE ENAME LIKE '%A%';

--2. EMP 테이블에서 J또는 A로 시작하는 사원의 이름을 출력하는 SQL작성(단, 첫 글자만 대문자이고 나머지 글자는 소문자이어야한다._
SELECT INITCAP(ENAME) NAME, LENGTH(ENAME) LENGTH
FROM EMP
WHERE ENAME LIKE 'J%' OR ENAME LIKE 'A%';

--3. EMP 테이블에서 이름의 글자 수가 6자 이상이 사원의 이르믈 소문자로 출력하는 SQL작성.
SELECT LOWER(ENAME) NAME, LENGTH(ENAME) LENGTH 
FROM EMP
WHERE LENGTH(ENAME) >= 6;


CREATE  TABLE  TABLE_CHECK (
  LOGIN_ID     VARCHAR2(20)  CONSTRAINT  TBLCK_LOGINID_PK  PRIMARY KEY,
  LOGIN_PWD  VARCHAR2(20)  CONSTRAINT  TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) > 3),
  TEL              VARCHAR2(20)
);

INSERT INTO TABLE_CHECK
VALUES ('TEST_ID','123','010-1111-2222');

INSERT INTO TABLE_CHECK
VALUES ('TEST_ID','1234','010-1111-2222');

SELECT * FROM TABLE_CHECK;

SELECT  OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
  FROM  USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'TABLE_CHECK';


CREATE  TABLE  TABLE_DEFAULT (
  LOGIN_ID     VARCHAR2(20)  CONSTRAINT  TBLDF_LOGINID_PK  PRIMARY KEY,
  LOGIN_PWD  VARCHAR2(20)  DEFAULT '1234',
  TEL              VARCHAR2(20)
);


--4.EMP 테이블을 이용하여 사원이름, 사원번호, 관리자이름, 관리자번호를 출력하는 SQL 작성. (등가조인)

SELECT E1.ENAME AS "사원이름", E1.EMPNO AS "사원번호", 
E2.ENAME AS "관리자이름", E2.EMPNO AS "관리자번호"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

SELECT  E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
 FROM EMP E  JOIN  DEPT D  ON ( E.DEPTNO = D.DEPTNO ) ;

SELECT  E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO, D.DNAME, D.LOC
 FROM EMP E  JOIN  DEPT D  ON ( E.DEPTNO = D.DEPTNO ) 
WHERE SAL <= 3000;


SELECT E1.ENAME 사원이름, E1.EMPNO 사원번호,
E2.ENAME 관리자이름, E2.EMPNO 관리자번호
FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO;
--등가조인이기 때문에 공통된 값이 없어서 KING 컬럼이 출력되지않는다.
--KING을 출력하고싶으면 OUTER JOIN 외부조인 해야됨. left, right, full조인이 있음.
--공통된 값이 없을때 외부조인 사용할것.

SELECT  E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO AS MGR_EMPNO, E2.ENAME AS MGR_ENAME
FROM EMP E1 LEFT OUTER JOIN EMP E2 ON ( E1.MGR=E2.EMPNO);
